[tools]
python = "3"
uv = "0"
ruff = "0"
ty = "0"

[bootstrap.packages]
# dev
"apk:musl-dev" = "latest"
"apk:libffi-dev" = "latest"
"apk:openssl-dev" = "latest"
"apk:zlib-dev" = "latest"
"apk:bzip2-dev" = "latest"
"apk:xz-dev" = "latest"
"apk:sqlite-dev" = "latest"
"apk:linux-headers" = "latest"
"apt:libc6-dev" = "latest"
"apt:libffi-dev" = "latest"
"apt:libssl-dev" = "latest"
"apt:zlib1g-dev" = "latest"
"apt:libbz2-dev" = "latest"
"apt:liblzma-dev" = "latest"
"apt:libsqlite3-dev" = "latest"
"apt:linux-libc-dev" = "latest"
"brew:openssl@3" = "latest"
"brew:libffi" = "latest"
"brew:xz" = "latest"
"brew:bzip2" = "latest"
"brew:sqlite" = "latest"
"brew:readline" = "latest"
"dnf:glibc-devel" = "latest"
"dnf:libffi-devel" = "latest"
"dnf:openssl-devel" = "latest"
"dnf:zlib-devel" = "latest"
"dnf:bzip2-devel" = "latest"
"dnf:xz-devel" = "latest"
"dnf:sqlite-devel" = "latest"
"dnf:kernel-headers" = "latest"
"pacman:glibc" = "latest"
"pacman:libffi" = "latest"
"pacman:openssl" = "latest"
"pacman:zlib" = "latest"
"pacman:bzip2" = "latest"
"pacman:xz" = "latest"
"pacman:sqlite" = "latest"
"pacman:linux-api-headers" = "latest"
"winget:Microsoft.WindowsSDK.10.0.26100" = "latest"
"winget:ShiningLight.OpenSSL.Dev" = "latest"
"zypper:glibc-devel" = "latest"
"zypper:libffi-devel" = "latest"
"zypper:libopenssl-devel" = "latest"
"zypper:zlib-devel" = "latest"
"zypper:libbz2-devel" = "latest"
"zypper:xz-devel" = "latest"
"zypper:sqlite3-devel" = "latest"
"zypper:linux-glibc-devel" = "latest"
# rt
"apk:musl" = "latest"
"apk:libffi" = "latest"
"apk:libssl3" = "latest"
"apk:libcrypto3" = "latest"
"apk:zlib" = "latest"
"apk:bzip2" = "latest"
"apk:xz-libs" = "latest"
"apk:sqlite-libs" = "latest"
"apt:libc6" = "latest"
"apt:libffi8" = "latest"
"apt:libssl3" = "latest"
"apt:zlib1g" = "latest"
"apt:libbz2-1.0" = "latest"
"apt:liblzma5" = "latest"
"apt:libsqlite3-0" = "latest"
# "brew:openssl@3" = "latest"
# "brew:libffi" = "latest"
# "brew:xz" = "latest"
# "brew:bzip2" = "latest"
# "brew:sqlite" = "latest"
# "brew:readline" = "latest"
"dnf:glibc" = "latest"
"dnf:libffi" = "latest"
"dnf:openssl-libs" = "latest"
"dnf:zlib" = "latest"
"dnf:bzip2-libs" = "latest"
"dnf:xz-libs" = "latest"
"dnf:sqlite-libs" = "latest"
# "pacman:glibc" = "latest"
# "pacman:libffi" = "latest"
# "pacman:openssl" = "latest"
# "pacman:zlib" = "latest"
# "pacman:bzip2" = "latest"
# "pacman:xz" = "latest"
# "pacman:sqlite" = "latest"
"winget:Microsoft.VCRedist.2015+.x64" = "latest"
"winget:ShiningLight.OpenSSL" = "latest"
"zypper:glibc" = "latest"
"zypper:libffi8" = "latest"
"zypper:libopenssl3" = "latest"
"zypper:libz1" = "latest"
"zypper:libbz2-1" = "latest"
"zypper:liblzma5" = "latest"
"zypper:libsqlite3-0" = "latest"
