[tools]
erlang = "29"
elixir = "1"
elixir-ls = "0"

[bootstrap.packages]
"apk:musl-dev" = "latest"
"apk:ncurses-dev" = "latest"
"apk:openssl-dev" = "latest"
"apk:zlib-dev" = "latest"
"apk:libstdc++-dev" = "latest"
"apk:linux-headers" = "latest"
"apt:libc6-dev" = "latest"
"apt:libncurses-dev" = "latest"
"apt:libssl-dev" = "latest"
"apt:zlib1g-dev" = "latest"
"apt:libstdc++-16-dev" = "latest"
"apt:linux-libc-dev" = "latest"
"brew:openssl@3" = "latest"
"brew:ncurses" = "latest"
"dnf:glibc-devel" = "latest"
"dnf:ncurses-devel" = "latest"
"dnf:openssl-devel" = "latest"
"dnf:zlib-devel" = "latest"
"dnf:libstdc++-devel" = "latest"
"dnf:kernel-headers" = "latest"
"pacman:glibc" = "latest"
"pacman:ncurses" = "latest"
"pacman:openssl" = "latest"
"pacman:zlib" = "latest"
"pacman:gcc-libs" = "latest"
"pacman:linux-api-headers" = "latest"
"winget:Microsoft.WindowsSDK.10.0.26100" = "latest"
"winget:ShiningLight.OpenSSL.Dev" = "latest"
"zypper:glibc-devel" = "latest"
"zypper:ncurses-devel" = "latest"
"zypper:libopenssl-devel" = "latest"
"zypper:zlib-devel" = "latest"
"zypper:libstdc++-devel" = "latest"
"zypper:linux-glibc-devel" = "latest"
"apk:musl" = "latest"
"apk:ncurses-libs" = "latest"
"apk:libcrypto3" = "latest"
"apk:libssl3" = "latest"
"apk:zlib" = "latest"
"apk:libstdc++" = "latest"
"apk:libgcc" = "latest"
"apt:libc6" = "latest"
"apt:libncurses6" = "latest"
"apt:libtinfo6" = "latest"
"apt:libssl3" = "latest"
"apt:zlib1g" = "latest"
"apt:libstdc++6" = "latest"
"apt:libgcc-s1" = "latest"
"dnf:glibc" = "latest"
"dnf:ncurses-libs" = "latest"
"dnf:openssl-libs" = "latest"
"dnf:zlib" = "latest"
"dnf:libstdc++" = "latest"
"dnf:libgcc" = "latest"
"winget:Microsoft.VCRedist.2015+.x64" = "latest"
"winget:ShiningLight.OpenSSL" = "latest"
"zypper:glibc" = "latest"
"zypper:libncurses6" = "latest"
"zypper:libopenssl3" = "latest"
"zypper:libz1" = "latest"
"zypper:libstdc++6" = "latest"
"zypper:libgcc_s1" = "latest"
