[tools]
ruby = "4"

[bootstrap.packages]
# dev
"apk:musl-dev" = "latest"
"apk:libffi-dev" = "latest"
"apk:yaml-dev" = "latest"
"apk:openssl-dev" = "latest"
"apk:zlib-dev" = "latest"
"apk:linux-headers" = "latest"
"apt:libc6-dev" = "latest"
"apt:libffi-dev" = "latest"
"apt:libyaml-dev" = "latest"
"apt:libssl-dev" = "latest"
"apt:zlib1g-dev" = "latest"
"apt:linux-libc-dev" = "latest"
"brew:openssl@3" = "latest"
"brew:libffi" = "latest"
"brew:libyaml" = "latest"
"brew:readline" = "latest"
"dnf:glibc-devel" = "latest"
"dnf:libffi-devel" = "latest"
"dnf:libyaml-devel" = "latest"
"dnf:openssl-devel" = "latest"
"dnf:zlib-devel" = "latest"
"dnf:kernel-headers" = "latest"
"pacman:glibc" = "latest"
"pacman:libffi" = "latest"
"pacman:libyaml" = "latest"
"pacman:openssl" = "latest"
"pacman:zlib" = "latest"
"pacman:linux-api-headers" = "latest"
"winget:Microsoft.WindowsSDK.10.0.26100" = "latest"
"winget:ShiningLight.OpenSSL.Dev" = "latest"
"zypper:glibc-devel" = "latest"
"zypper:libffi-devel" = "latest"
"zypper:libyaml-devel" = "latest"
"zypper:libopenssl-devel" = "latest"
"zypper:zlib-devel" = "latest"
"zypper:linux-glibc-devel" = "latest"
# rt
"apk:musl" = "latest"
"apk:libffi" = "latest"
"apk:yaml" = "latest"
"apk:libssl3" = "latest"
"apk:libcrypto3" = "latest"
"apk:zlib" = "latest"
"apt:libc6" = "latest"
"apt:libffi8" = "latest"
"apt:libyaml-0-2" = "latest"
"apt:libssl3" = "latest"
"apt:zlib1g" = "latest"
# "brew:openssl@3" = "latest"
# "brew:libffi" = "latest"
# "brew:libyaml" = "latest"
# "brew:readline" = "latest"
"dnf:glibc" = "latest"
"dnf:libffi" = "latest"
"dnf:libyaml" = "latest"
"dnf:openssl-libs" = "latest"
"dnf:zlib" = "latest"
# "pacman:glibc" = "latest"
# "pacman:libffi" = "latest"
# "pacman:libyaml" = "latest"
# "pacman:openssl" = "latest"
# "pacman:zlib" = "latest"
"winget:Microsoft.VCRedist.2015+.x64" = "latest"
"winget:ShiningLight.OpenSSL" = "latest"
"zypper:glibc" = "latest"
"zypper:libffi8" = "latest"
"zypper:libyaml-0-2" = "latest"
"zypper:libopenssl3" = "latest"
"zypper:libz1" = "latest"
