min_version = "2026.10.4"

[settings]
lockfile = true
experimental = true

[env]
PROXY_URI = "{{ env?.VSCODE_PROXY_URI or 'http://localhost:{{port}}' }}"
HK_MISE = 1
HK_PROFILE = "{{ mise_env | default(value=[]) | join(sep=',') }}"
PITCHFORK_WEB_PORT = 3120

[tools]
betterleaks = "1"
fnox = "1"
hk = "2"
"github:protonpass/pass-cli" = "2"
pitchfork = "2"
pkl = "0"
tombi = "1"
updatecli = "0"

[daemons.fnox]
run = "exec fnox daemon start"

[tasks."check:all"]
run = "hk check --all"

[tasks."check:diff"]
run = "hk check"

[tasks."fix:all"]
run = "hk fix --all"

[tasks."fix:diff"]
run = "hk fix --all"

[tasks."pre-commit:all"]
run = "hk run pre-commit --all"

[tasks."pre-commit:diff"]
run = "hk run pre-commit --all"

[tasks."pre-push:all"]
run = "hk run pre-push --all"

[tasks."pre-push:diff"]
run = "hk run pre-push --all"

[tasks."updatecli:check"]
run = "updatecli diff --config .config/updatecli/"

[tasks."updatecli:apply"]
run = "updatecli apply --config .config/updatecli/"

[tasks.release]
run = "goreleaser release --clean"

[tasks."dev-setup:hk"]
run = "hk install --mise"

[tasks."dev-setup:proton-pass"]
secrets = ["PROTON_PASS_PERSONAL_ACCESS_TOKEN"]
run = '''
if ! pass-cli info; then
    pass-cli logout
    pass-cli login
fi
'''

[tasks."dev-setup:fnox"]
depends = "dev-setup:proton-pass"
daemons = "fnox"
run = "fnox daemon start"

[secrets.fnox]
