[tools]
dotnet = "10"

[bootstrap.packages]
"apk:musl-dev" = "latest"
"apk:libstdc++-dev" = "latest"
"apk:icu-dev" = "latest"
"apk:openssl-dev" = "latest"
"apk:zlib-dev" = "latest"
"apk:krb5-dev" = "latest"
"apk:linux-headers" = "latest"
"apt:libc6-dev" = "latest"
"apt:libstdc++-16-dev" = "latest"
"apt:libicu-dev" = "latest"
"apt:libssl-dev" = "latest"
"apt:zlib1g-dev" = "latest"
"apt:libkrb5-dev" = "latest"
"apt:linux-libc-dev" = "latest"
"brew:openssl@3" = "latest"
"brew:icu4c" = "latest"
"dnf:glibc-devel" = "latest"
"dnf:libstdc++-devel" = "latest"
"dnf:libicu-devel" = "latest"
"dnf:openssl-devel" = "latest"
"dnf:zlib-devel" = "latest"
"dnf:krb5-devel" = "latest"
"dnf:kernel-headers" = "latest"
"pacman:glibc" = "latest"
"pacman:gcc-libs" = "latest"
"pacman:icu" = "latest"
"pacman:openssl" = "latest"
"pacman:zlib" = "latest"
"pacman:krb5" = "latest"
"pacman:linux-api-headers" = "latest"
"winget:Microsoft.WindowsSDK.10.0.26100" = "latest"
"zypper:glibc-devel" = "latest"
"zypper:libstdc++-devel" = "latest"
"zypper:libicu-devel" = "latest"
"zypper:libopenssl-devel" = "latest"
"zypper:zlib-devel" = "latest"
"zypper:krb5-devel" = "latest"
"zypper:linux-glibc-devel" = "latest"
"apk:musl" = "latest"
"apk:libstdc++" = "latest"
"apk:libgcc" = "latest"
"apk:icu-libs" = "latest"
"apk:libssl3" = "latest"
"apk:libcrypto3" = "latest"
"apk:zlib" = "latest"
"apk:krb5-libs" = "latest"
"apt:libc6" = "latest"
"apt:libstdc++6" = "latest"
"apt:libgcc-s1" = "latest"
"apt:libicu78" = "latest"
"apt:libssl3" = "latest"
"apt:zlib1g" = "latest"
"apt:libgssapi-krb5-2" = "latest"
"dnf:glibc" = "latest"
"dnf:libstdc++" = "latest"
"dnf:libgcc" = "latest"
"dnf:libicu" = "latest"
"dnf:openssl-libs" = "latest"
"dnf:zlib" = "latest"
"dnf:krb5-libs" = "latest"
"winget:Microsoft.VCRedist.2015+.x64" = "latest"
"zypper:glibc" = "latest"
"zypper:libstdc++6" = "latest"
"zypper:libgcc_s1" = "latest"
"zypper:libicu73" = "latest"
"zypper:libopenssl3" = "latest"
"zypper:libz1" = "latest"
"zypper:krb5" = "latest"
