[tools]
java = "27"

[bootstrap.packages]
# dev
"apk:musl-dev" = "latest"
"apk:libstdc++-dev" = "latest"
"apk:zlib-dev" = "latest"
"apk:linux-headers" = "latest"
"apt:libc6-dev" = "latest"
"apt:libstdc++-16-dev" = "latest"
"apt:zlib1g-dev" = "latest"
"apt:linux-libc-dev" = "latest"
"dnf:glibc-devel" = "latest"
"dnf:libstdc++-devel" = "latest"
"dnf:zlib-devel" = "latest"
"dnf:kernel-headers" = "latest"
"pacman:glibc" = "latest"
"pacman:gcc-libs" = "latest"
"pacman:zlib" = "latest"
"pacman:linux-api-headers" = "latest"
"winget:Microsoft.WindowsSDK.10.0.26100" = "latest"
"zypper:glibc-devel" = "latest"
"zypper:libstdc++-devel" = "latest"
"zypper:zlib-devel" = "latest"
"zypper:linux-glibc-devel" = "latest"
# rt
"apk:musl" = "latest"
"apk:zlib" = "latest"
"apk:libstdc++" = "latest"
"apk:libgcc" = "latest"
"apt:libc6" = "latest"
"apt:zlib1g" = "latest"
"apt:libstdc++6" = "latest"
"apt:libgcc-s1" = "latest"
"dnf:glibc" = "latest"
"dnf:zlib" = "latest"
"dnf:libstdc++" = "latest"
"dnf:libgcc" = "latest"
# "pacman:glibc" = "latest"
# "pacman:zlib" = "latest"
# "pacman:gcc-libs" = "latest"
"winget:Microsoft.VCRedist.2015+.x64" = "latest"
"zypper:glibc" = "latest"
"zypper:libz1" = "latest"
"zypper:libstdc++6" = "latest"
"zypper:libgcc_s1" = "latest"
