[tools]
php = "8"

[env._.php]
prebuilt_static = true

[bootstrap.packages]
# dev
"apk:musl-dev" = "latest"
"apk:libffi-dev" = "latest"
"apk:pcre2-dev" = "latest"
"apk:zlib-dev" = "latest"
"apk:libxml2-dev" = "latest"
"apk:openssl-dev" = "latest"
"apk:linux-headers" = "latest"
"apt:libc6-dev" = "latest"
"apt:libffi-dev" = "latest"
"apt:libpcre2-dev" = "latest"
"apt:zlib1g-dev" = "latest"
"apt:libxml2-dev" = "latest"
"apt:libssl-dev" = "latest"
"apt:linux-libc-dev" = "latest"
"brew:openssl@3" = "latest"
"brew:libffi" = "latest"
"brew:pcre2" = "latest"
"brew:libxml2" = "latest"
"dnf:glibc-devel" = "latest"
"dnf:libffi-devel" = "latest"
"dnf:pcre2-devel" = "latest"
"dnf:zlib-devel" = "latest"
"dnf:libxml2-devel" = "latest"
"dnf:openssl-devel" = "latest"
"dnf:kernel-headers" = "latest"
"pacman:glibc" = "latest"
"pacman:libffi" = "latest"
"pacman:pcre2" = "latest"
"pacman:zlib" = "latest"
"pacman:libxml2" = "latest"
"pacman:openssl" = "latest"
"pacman:linux-api-headers" = "latest"
"winget:Microsoft.WindowsSDK.10.0.26100" = "latest"
"winget:ShiningLight.OpenSSL.Dev" = "latest"
"zypper:glibc-devel" = "latest"
"zypper:libffi-devel" = "latest"
"zypper:pcre2-devel" = "latest"
"zypper:zlib-devel" = "latest"
"zypper:libxml2-devel" = "latest"
"zypper:libopenssl-devel" = "latest"
"zypper:linux-glibc-devel" = "latest"
# rt
"apk:musl" = "latest"
"apk:libffi" = "latest"
"apk:pcre2" = "latest"
"apk:zlib" = "latest"
"apk:libxml2" = "latest"
"apk:libssl3" = "latest"
"apk:libcrypto3" = "latest"
"apt:libc6" = "latest"
"apt:libffi8" = "latest"
"apt:libpcre2-8-0" = "latest"
"apt:zlib1g" = "latest"
"apt:libxml2-16" = "latest"
"apt:libssl3" = "latest"
# "brew:openssl@3" = "latest"
# "brew:libffi" = "latest"
# "brew:pcre2" = "latest"
# "brew:libxml2" = "latest"
"dnf:glibc" = "latest"
"dnf:libffi" = "latest"
"dnf:pcre2" = "latest"
"dnf:zlib" = "latest"
"dnf:libxml2" = "latest"
"dnf:openssl-libs" = "latest"
# "pacman:glibc" = "latest"
# "pacman:libffi" = "latest"
# "pacman:pcre2" = "latest"
# "pacman:zlib" = "latest"
# "pacman:libxml2" = "latest"
# "pacman:openssl" = "latest"
"winget:Microsoft.VCRedist.2015+.x64" = "latest"
"winget:ShiningLight.OpenSSL" = "latest"
"zypper:glibc" = "latest"
"zypper:libffi8" = "latest"
"zypper:libpcre2-8-0" = "latest"
"zypper:libz1" = "latest"
"zypper:libxml2-2" = "latest"
"zypper:libopenssl3" = "latest"
